# Generated by Django 5.0.1 on 2024-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('storypoint', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('InProgress', 'InProgress'), ('Complete', 'Complete')], default='Assigned', max_length=20)),
            ],
        ),
    ]
